import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const runtimeFiles = JSON.parse(await readFile(path.join(packageRoot, "runtime-files.json"), "utf8"));
const sources = runtimeFiles.classic;
const sections = [];
for (const file of sources) {
  const source = await readFile(path.join(packageRoot, file), "utf8");
  sections.push(`/* ${file} */\n${source.trim()}\n`);
}

sections.push(`(function (root) {
  "use strict";
  var runtime = root[Symbol.for("niva.node-compat.runtime")];
  if (!root.Niva) throw new Error("Load the Niva initialize script before node-compat.");
  root.NivaNodeCompatReady = runtime.registerNodeCompat(root.Niva);
})(globalThis);`);

const banner = "/* Generated by scripts/build-classic.mjs. Edit src/runtime/*.js instead. */\n";
await mkdir(path.join(packageRoot, "dist"), { recursive: true });
await writeFile(path.join(packageRoot, "dist/niva-node-compat.js"), banner + sections.join("\n"), "utf8");
process.stdout.write("Built dist/niva-node-compat.js\n");
