import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sources = [
  "src/runtime/bridge.js",
  "src/runtime/path.js",
  "src/runtime/events.js",
  "src/runtime/querystring.js",
  "src/runtime/buffer.js",
  "src/runtime/util.js",
  "src/runtime/os.js",
  "src/runtime/fs.js",
  "src/runtime/child_process.js",
  "src/runtime/url.js",
  "src/runtime/crypto.js",
  "src/runtime/zlib.js",
  "src/runtime/assert.js",
  "src/runtime/http.js",
  "src/runtime/stream.js",
  "src/runtime/registration.js",
];

const sections = await Promise.all(sources.map(async (file) => {
  const source = await readFile(path.join(packageRoot, file), "utf8");
  return `/* ${file} */\n${source.trim()}\n`;
}));

sections.push(`(function (root) {
  "use strict";
  var runtime = root[Symbol.for("niva.node-compat.runtime")];
  if (!root.Niva) throw new Error("Load the Niva initialize script before node-compat.");
  root.NivaNodeCompatReady = runtime.registerNodeCompat(root.Niva);
})(globalThis);`);

const banner = "/* Generated by scripts/build-classic.mjs. Edit src/runtime/*.js instead. */\n";
await mkdir(path.join(packageRoot, "dist"), { recursive: true });
await writeFile(path.join(packageRoot, "dist/niva-node-compat.js"), banner + sections.join("\n"), "utf8");
process.stdout.write("Built dist/niva-node-compat.js\n");
