[package]
name = "niva"
description = "A lightweight Tauri alternative"
version = "0.9.9"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

wry = { version = "0.57.0", features = ["devtools"] }
tao = { version = "0.37.0", features = ["serde"] }
muda = "0.20.0"
tray-icon = "0.25.1"
global-hotkey = "0.8.0"
arboard = "3.6.1"
ureq = { version = "3.4.2", default-features = false, features = [
	"native-tls",
	"native-tls-webpki-roots",
	"gzip",
] }
native-tls = "0.2.18"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
mime_guess = "2.0.5"
os_info = "3.15.0"
directories = "6.0.0"
opener = "0.8.5"
rfd = { version = "0.17.2", default-features = false, features = [
	"xdg-portal",
] }
anyhow = "1.0.104"
smol = "2"
tungstenite = "0.30"
getrandom = "0.3"
async-channel = "2"
flate2 = "1.1.10"
png = "0.18.1"
sys-locale = "0.3.2"
url = "2.5.8"
glob = "0.3.4"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-foundation = "0.3.2"
objc2-app-kit = "0.3.2"
x-win = "5.8.0"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_System_LibraryLoader"] }
