//! Convert the VERSIONINFO `.rc` text emitted by devtools into a Windows
//! `VS_VERSIONINFO` resource. Keeping this encoder portable lets the binary
//! format be checked on non-Windows hosts before touching an executable.

use std::collections::BTreeMap;

use anyhow::{Context, Result, anyhow, bail};

/// Compile the small, deterministic VERSIONINFO dialect generated by
/// `windows-version-info-template.ts` into the binary format expected by
/// `UpdateResourceW(RT_VERSION, ...)`.
pub fn compile_version_info_rc(source: &str) -> Result<Vec<u8>> {
    let source = source.strip_prefix('\u{feff}').unwrap_or(source);
    let mut has_version_info = false;
    let mut file_version = None;
    let mut product_version = None;
    let mut file_os = None;
    let mut file_type = None;
    let mut file_subtype = 0;
    let mut file_flags_mask = 0x3f;
    let mut file_flags = 0;
    let mut translation = (0x0409, 0x04b0);
    let mut strings = BTreeMap::new();

    for line in source.lines().map(str::trim) {
        if line.is_empty() || line.starts_with("//") {
            continue;
        }
        let mut words = line.split_whitespace();
        let directive = words.next().unwrap_or_default();
        let value = words.collect::<Vec<_>>().join(" ");
        match directive {
            "VERSIONINFO" => has_version_info = true,
            "FILEVERSION" => file_version = Some(parse_version(&value).context("FILEVERSION")?),
            "PRODUCTVERSION" => {
                product_version = Some(parse_version(&value).context("PRODUCTVERSION")?)
            }
            "FILEOS" => file_os = Some(parse_number(&value).context("FILEOS")?),
            "FILETYPE" => file_type = Some(parse_number(&value).context("FILETYPE")?),
            "FILESUBTYPE" => file_subtype = parse_number(&value).context("FILESUBTYPE")?,
            "FILEFLAGS" => file_flags = parse_number(&value).context("FILEFLAGS")?,
            "FILEFLAGSMASK" => file_flags_mask = parse_number(&value).context("FILEFLAGSMASK")?,
            "VALUE" => {
                let (key, remainder) =
                    parse_json_string(&line["VALUE".len()..]).context("VERSIONINFO VALUE key")?;
                let remainder = remainder.trim_start();
                let value_text = remainder
                    .strip_prefix(',')
                    .ok_or_else(|| anyhow!("VERSIONINFO VALUE is missing a comma"))?
                    .trim_start();
                if key == "Translation" {
                    let parts = parse_number_list(value_text).context("Translation")?;
                    if parts.len() != 2 {
                        bail!("Translation must contain a language and code page");
                    }
                    translation = (
                        u16::try_from(parts[0]).context("Translation language is out of range")?,
                        u16::try_from(parts[1]).context("Translation code page is out of range")?,
                    );
                } else {
                    let (value, trailing) = if value_text.starts_with('"') {
                        parse_json_string(value_text).context("VERSIONINFO VALUE string")?
                    } else if value_text == "undefined" {
                        // Older devtools configs can omit optional metadata. The template
                        // interpolates JSON.stringify(undefined) as the bare token here.
                        (String::new(), "")
                    } else {
                        bail!("unsupported VERSIONINFO string value for {key:?}");
                    };
                    if !trailing.trim().is_empty() {
                        bail!("unexpected text after VERSIONINFO value for {key:?}");
                    }
                    strings.insert(key, value);
                }
            }
            _ => {
                if let Some((id, kind)) = line.split_once(char::is_whitespace)
                    && kind.trim() == "VERSIONINFO"
                {
                    if id != "1" {
                        bail!("only VERSIONINFO resource ID 1 is supported, got {id:?}");
                    }
                    has_version_info = true;
                }
            }
        }
    }

    if !has_version_info {
        bail!("VERSIONINFO declaration not found");
    }

    let file_version = file_version.ok_or_else(|| anyhow!("FILEVERSION not found"))?;
    let product_version = product_version.ok_or_else(|| anyhow!("PRODUCTVERSION not found"))?;
    let mut fixed = Vec::with_capacity(52);
    for value in [
        0xFEEF04BD,
        0x00010000,
        pack_version(file_version),
        pack_version_low(file_version),
        pack_version(product_version),
        pack_version_low(product_version),
        file_flags_mask,
        file_flags,
        file_os.unwrap_or(0x00040004),
        file_type.unwrap_or(1),
        file_subtype,
        0,
        0,
    ] {
        fixed.extend_from_slice(&value.to_le_bytes());
    }

    let mut string_children = Vec::with_capacity(strings.len());
    for (key, value) in strings {
        let mut utf16_value: Vec<u16> = value.encode_utf16().collect();
        utf16_value.push(0);
        let value_len =
            u16::try_from(utf16_value.len()).context("VERSIONINFO string is too long")?;
        let mut value_bytes = Vec::with_capacity(utf16_value.len() * 2);
        for unit in utf16_value {
            value_bytes.extend_from_slice(&unit.to_le_bytes());
        }
        string_children.push(encode_block(&key, 1, value_len, &value_bytes, &[])?);
    }

    let table_key = format!("{:04x}{:04x}", translation.0, translation.1);
    let string_table = encode_block(&table_key, 1, 0, &[], &string_children)?;
    let string_file_info = encode_block("StringFileInfo", 1, 0, &[], &[string_table])?;

    let mut translation_bytes = Vec::with_capacity(4);
    translation_bytes.extend_from_slice(&translation.0.to_le_bytes());
    translation_bytes.extend_from_slice(&translation.1.to_le_bytes());
    let translation_block = encode_block("Translation", 0, 4, &translation_bytes, &[])?;
    let var_file_info = encode_block("VarFileInfo", 1, 0, &[], &[translation_block])?;

    encode_block(
        "VS_VERSION_INFO",
        0,
        52,
        &fixed,
        &[string_file_info, var_file_info],
    )
}

fn parse_version(input: &str) -> Result<[u16; 4]> {
    let parts = parse_number_list(input)?;
    if parts.len() != 4 {
        bail!("expected four comma-separated version components, got {input:?}");
    }
    Ok([
        u16::try_from(parts[0]).context("version component is out of range")?,
        u16::try_from(parts[1]).context("version component is out of range")?,
        u16::try_from(parts[2]).context("version component is out of range")?,
        u16::try_from(parts[3]).context("version component is out of range")?,
    ])
}

fn parse_number_list(input: &str) -> Result<Vec<u32>> {
    input
        .split(|ch: char| ch == ',' || ch.is_whitespace())
        .filter(|part| !part.is_empty())
        .map(parse_number)
        .collect()
}

fn parse_number(input: &str) -> Result<u32> {
    let input = input.trim().trim_end_matches(';');
    if let Some(hex) = input
        .strip_prefix("0x")
        .or_else(|| input.strip_prefix("0X"))
    {
        Ok(u32::from_str_radix(hex, 16).with_context(|| format!("invalid number {input:?}"))?)
    } else {
        Ok(input
            .parse()
            .with_context(|| format!("invalid number {input:?}"))?)
    }
}

fn parse_json_string(input: &str) -> Result<(String, &str)> {
    let input = input.trim_start();
    if !input.starts_with('"') {
        bail!("expected a quoted string");
    }
    let bytes = input.as_bytes();
    let mut escaped = false;
    for (index, byte) in bytes.iter().enumerate().skip(1) {
        if escaped {
            escaped = false;
        } else if *byte == b'\\' {
            escaped = true;
        } else if *byte == b'"' {
            let (quoted, remainder) = input.split_at(index + 1);
            let value = serde_json::from_str(quoted).context("invalid quoted string")?;
            return Ok((value, remainder));
        }
    }
    bail!("unterminated quoted string")
}

fn pack_version(version: [u16; 4]) -> u32 {
    (u32::from(version[0]) << 16) | u32::from(version[1])
}

fn pack_version_low(version: [u16; 4]) -> u32 {
    (u32::from(version[2]) << 16) | u32::from(version[3])
}

fn encode_block(
    key: &str,
    kind: u16,
    value_len: u16,
    value: &[u8],
    children: &[Vec<u8>],
) -> Result<Vec<u8>> {
    let mut block = Vec::new();
    block.extend_from_slice(&[0, 0]); // wLength, filled after encoding.
    block.extend_from_slice(&value_len.to_le_bytes());
    block.extend_from_slice(&kind.to_le_bytes());
    for unit in key.encode_utf16().chain(std::iter::once(0)) {
        block.extend_from_slice(&unit.to_le_bytes());
    }
    align_dword(&mut block);
    block.extend_from_slice(value);
    if !children.is_empty() {
        // This padding aligns the first child and belongs to this block.
        // A leaf block's wLength must stop before padding for its next sibling.
        align_dword(&mut block);
    }
    for child in children {
        align_dword(&mut block);
        block.extend_from_slice(child);
    }
    let length = u16::try_from(block.len()).context("VERSIONINFO resource exceeds 64 KiB")?;
    block[..2].copy_from_slice(&length.to_le_bytes());
    Ok(block)
}

fn align_dword(bytes: &mut Vec<u8>) {
    while bytes.len() % 4 != 0 {
        bytes.push(0);
    }
}

#[cfg(test)]
mod tests {
    use super::compile_version_info_rc;

    const VERSION_RC: &str = r#"
1 VERSIONINFO
FILEVERSION 1,2,3,4
PRODUCTVERSION 5,6,7,8
FILEOS 0x40004
FILETYPE 0x1
{
BLOCK "StringFileInfo"
{
  BLOCK "040904b0"
  {
    VALUE "CompanyName", "Museum \"Labs\""
    VALUE "FileDescription", "Músée"
    VALUE "ProductVersion", "5.6.7.8"
  }
}
BLOCK "VarFileInfo"
{
  VALUE "Translation", 0x0409 0x04B0
}
}
"#;

    #[test]
    fn emits_aligned_version_resource_with_fixed_file_info() {
        let bytes = compile_version_info_rc(VERSION_RC).unwrap();
        assert_eq!(
            u16::from_le_bytes([bytes[0], bytes[1]]) as usize,
            bytes.len()
        );
        assert_eq!(u16::from_le_bytes([bytes[2], bytes[3]]), 52);
        assert_eq!(u16::from_le_bytes([bytes[4], bytes[5]]), 0);

        // The VS_FIXEDFILEINFO value begins after the six-byte header, the
        // null-terminated VS_VERSION_INFO key, and DWORD alignment.
        let fixed_offset = 40;
        assert_eq!(
            u32::from_le_bytes(bytes[fixed_offset..fixed_offset + 4].try_into().unwrap()),
            0xFEEF04BD
        );
        assert_eq!(
            u32::from_le_bytes(
                bytes[fixed_offset + 8..fixed_offset + 12]
                    .try_into()
                    .unwrap()
            ),
            (1 << 16) | 2
        );
        assert_eq!(
            u32::from_le_bytes(
                bytes[fixed_offset + 12..fixed_offset + 16]
                    .try_into()
                    .unwrap()
            ),
            (3 << 16) | 4
        );
        assert!(bytes.windows("StringFileInfo".len() * 2).any(|window| {
            window
                .chunks_exact(2)
                .map(|pair| u16::from_le_bytes([pair[0], pair[1]]))
                .eq("StringFileInfo".encode_utf16())
        }));
        assert!(
            bytes
                .windows("Museum \"Labs\"".encode_utf16().count() * 2)
                .any(|window| {
                    window
                        .chunks_exact(2)
                        .map(|pair| u16::from_le_bytes([pair[0], pair[1]]))
                        .eq("Museum \"Labs\"".encode_utf16())
                })
        );
    }

    #[test]
    fn rejects_malformed_rc_version_fields() {
        let invalid = VERSION_RC.replace("FILEVERSION 1,2,3,4", "FILEVERSION 1,2");
        let error = compile_version_info_rc(&invalid).unwrap_err().to_string();
        assert!(error.contains("FILEVERSION"));
    }
}
